/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e2ec",
        secondary: "#5f5693",
        "secondary-fixed-dim": "#c8bfff",
        "outline-variant": "#c1c6d5",
        "on-primary-container": "#f4fffc",
        "surface-container-high": "#e6e8f1",
        primary: "#00685f",
        "on-tertiary-container": "#fffbff",
        "on-background": "#181c22",
        "inverse-on-surface": "#eff0fa",
        "inverse-primary": "#78d7ca",
        "on-surface-variant": "#414753",
        "surface-variant": "#e0e2ec",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e5deff",
        "on-secondary-container": "#4f4782",
        "on-tertiary-fixed-variant": "#494459",
        "on-primary-fixed-variant": "#005049",
        "on-error-container": "#93000a",
        "secondary-container": "#c3b9fd",
        "on-secondary-fixed-variant": "#473f7a",
        tertiary: "#5e596f",
        "on-primary-fixed": "#00201d",
        "primary-fixed": "#94f3e6",
        surface: "#f9f9ff",
        "on-secondary-fixed": "#1b104c",
        "tertiary-fixed": "#e7def9",
        "on-surface": "#181c22",
        "on-tertiary-fixed": "#1d192c",
        "surface-bright": "#f9f9ff",
        "surface-container": "#ecedf7",
        "tertiary-container": "#777188",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#cbc3dd",
        "surface-tint": "#006a61",
        "inverse-surface": "#2d3038",
        background: "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f3fd",
        "surface-dim": "#d8dae3",
        "primary-fixed-dim": "#78d7ca",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#108378",
        error: "#ba1a1a",
        outline: "#717785"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin_desktop: "40px",
        gutter: "16px",
        margin_mobile: "16px",
        container_max: "1200px",
        unit: "8px",
        margin: "24px",
        lg: "24px",
        sm: "8px",
        md: "16px",
        base: "8px",
        xs: "4px",
        xl: "32px"
      },
      fontFamily: {
        h1: ["Inter"],
        "h1-mobile": ["Inter"],
        h2: ["Inter"],
        h3: ["Inter"],
        "label-sm": ["Inter"],
        body: ["Inter"],
        interactive: ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["30px", { lineHeight: "1.3", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        interactive: ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
